name: 'E0ShopManager'
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  geolocator: ^3.0.1
  http: ^0.12.2
  flutter_spinkit: ^4.1.2
  intl: ^0.16.1
  json_annotation: ^3.0.1
  file_picker_cross: ^4.2.2
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - images/

